/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './app.component.css.shim';
import * as import11 from './ng2-responsive/responsive/responsive.ngfactory';
import * as import12 from './ng2-responsive/responsive-window/responsive-window.ngfactory';
import * as import13 from './ng2-responsive/bootstrap/bootstrap-directives.ngfactory';
import * as import14 from './ng2-responsive/devices/devices-directives.ngfactory';
import * as import15 from './ng2-responsive/pixelratio/pixelratio-directives.ngfactory';
import * as import16 from './ng2-responsive/useragent/useragent.ngfactory';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '../../../src/app/ng2-responsive/config/config';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '../../../src/app/ng2-responsive/responsive/responsive';
import * as import21 from '../../../src/app/ng2-responsive/responsive-window/responsive-window';
import * as import22 from '../../../src/app/ng2-responsive/bootstrap/bootstrap-directives';
import * as import23 from '../../../src/app/ng2-responsive/devices/devices-directives';
import * as import24 from '../../../src/app/ng2-responsive/pixelratio/pixelratio-directives';
import * as import25 from '../../../src/app/ng2-responsive/useragent/useragent';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-app',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import9.ComponentFactory<import0.AppComponent> = new import9.ComponentFactory<import0.AppComponent>('my-app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import10.styles];
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _anchor_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _TemplateRef_42_5:any;
  _Responsive_42_6:import11.Wrapper_Responsive;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _TemplateRef_44_5:any;
  _Responsive_44_6:import11.Wrapper_Responsive;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _ResponsiveWindow_47_3:import12.Wrapper_ResponsiveWindow;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _appEl_49:import3.AppElement;
  _TemplateRef_49_5:any;
  _Responsive_49_6:import11.Wrapper_Responsive;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import3.AppElement;
  _ResponsiveSizeInfo_67_5:import13.Wrapper_ResponsiveSizeInfo;
  _text_68:any;
  _el_69:any;
  /*private*/ _appEl_69:import3.AppElement;
  _DeviceInfo_69_5:import14.Wrapper_DeviceInfo;
  _text_70:any;
  _el_71:any;
  /*private*/ _appEl_71:import3.AppElement;
  _OrientationInfo_71_5:import14.Wrapper_OrientationInfo;
  _text_72:any;
  _el_73:any;
  /*private*/ _appEl_73:import3.AppElement;
  _PixelRatioInfo_73_5:import15.Wrapper_PixelRatioInfo;
  _text_74:any;
  _el_75:any;
  _UserAgentInfo_75_3:import16.Wrapper_UserAgentInfo;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _arr_0:any;
  _map_0:any;
  _arr_1:any;
  _map_1:any;
  _map_2:any;
  _map_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'main',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','background-image');
    this.renderer.setElementAttribute(this._el_2,'src','../assets/images/background-responsive-directives.jpg');
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','site-wrapper');
    this.renderer.setElementAttribute(this._el_4,'style','min-height:700px;');
    this._text_5 = this.renderer.createText(this._el_4,'\n\n  ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','site-wrapper-inner');
    this._text_7 = this.renderer.createText(this._el_6,'\n\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','cover-container');
    this._text_9 = this.renderer.createText(this._el_8,'\n\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','masthead clearfix');
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','inner');
    this._text_13 = this.renderer.createText(this._el_12,'\n          ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'nav',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','nav masthead-nav');
    this._text_17 = this.renderer.createText(this._el_16,'\n              ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'li',(null as any));
    this._el_19 = this.renderer.createElement(this._el_18,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'href','https://github.com/ManuCutillas/responsive-directives-angular2');
    this._text_20 = this.renderer.createText(this._el_19,'Github',(null as any));
    this._text_21 = this.renderer.createText(this._el_16,'\n              ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_16,'li',(null as any));
    this._el_23 = this.renderer.createElement(this._el_22,'a',(null as any));
    this.renderer.setElementAttribute(this._el_23,'href','https://www.npmjs.com/package/responsive-directives-angular2');
    this._text_24 = this.renderer.createText(this._el_23,'NPM',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n              ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_16,'li',(null as any));
    this._el_27 = this.renderer.createElement(this._el_26,'a',(null as any));
    this.renderer.setElementAttribute(this._el_27,'href','https://github.com/ManuCutillas/responsive-directives-angular2/issues');
    this._text_28 = this.renderer.createText(this._el_27,'issues',(null as any));
    this._text_29 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._text_31 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._text_33 = this.renderer.createText(this._el_8,'\n\n      ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','inner cover');
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'img',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','rd-logo');
    this.renderer.setElementAttribute(this._el_36,'src','../assets/images/logo-responsive.png');
    this._text_37 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_34,'p',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','lead introduction');
    this._text_39 = this.renderer.createText(this._el_38,'Superset of RESPONSIVE DIRECTIVES to show or hide items according to the size of the device screen and another features in Angular 2',(null as any));
    this._text_40 = this.renderer.createText(this._el_34,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._anchor_42 = this.renderer.createTemplateAnchor(this._el_8,(null as any));
    this._appEl_42 = new import3.AppElement(42,8,this,this._anchor_42);
    this._TemplateRef_42_5 = new import17.TemplateRef_(this._appEl_42,viewFactory_AppComponent1);
    this._Responsive_42_6 = new import11.Wrapper_Responsive(this._TemplateRef_42_5,this.parentInjector.get(import18.ResponsiveState),this._appEl_42.vcRef);
    this._text_43 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_8,(null as any));
    this._appEl_44 = new import3.AppElement(44,8,this,this._anchor_44);
    this._TemplateRef_44_5 = new import17.TemplateRef_(this._appEl_44,viewFactory_AppComponent2);
    this._Responsive_44_6 = new import11.Wrapper_Responsive(this._TemplateRef_44_5,this.parentInjector.get(import18.ResponsiveState),this._appEl_44.vcRef);
    this._text_45 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_46 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_47,'style','position:absolute; width:100%;');
    this._ResponsiveWindow_47_3 = new import12.Wrapper_ResponsiveWindow(this.parentInjector.get(import18.ResponsiveState),new import19.ElementRef(this._el_47));
    this._text_48 = this.renderer.createText(this._el_47,'\n              ',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._appEl_49 = new import3.AppElement(49,47,this,this._anchor_49);
    this._TemplateRef_49_5 = new import17.TemplateRef_(this._appEl_49,viewFactory_AppComponent3);
    this._Responsive_49_6 = new import11.Wrapper_Responsive(this._TemplateRef_49_5,this.parentInjector.get(import18.ResponsiveState),this._appEl_49.vcRef);
    this._text_50 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_8,'\n\n      ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','mastfoot');
    this._text_53 = this.renderer.createText(this._el_52,'\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','inner follow');
    this._text_55 = this.renderer.createText(this._el_54,'\n          ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'p',(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Please give me a star on ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'a',(null as any));
    this.renderer.setElementAttribute(this._el_58,'href','https://github.com/ManuCutillas/responsive-directives-angular2');
    this._text_59 = this.renderer.createText(this._el_58,'Github',(null as any));
    this._text_60 = this.renderer.createText(this._el_56,', Follow me on ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_56,'a',(null as any));
    this.renderer.setElementAttribute(this._el_61,'href','https://twitter.com/ManuCutillas');
    this._text_62 = this.renderer.createText(this._el_61,'@ManuCutillas',(null as any));
    this._text_63 = this.renderer.createText(this._el_56,'.',(null as any));
    this._text_64 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_52,'\n      ',(null as any));
    this._text_66 = this.renderer.createText(this._el_8,'\n       ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_8,'responsiveSizeInfo',(null as any));
    this._appEl_67 = new import3.AppElement(67,8,this,this._el_67);
    this._ResponsiveSizeInfo_67_5 = new import13.Wrapper_ResponsiveSizeInfo(this.parentInjector.get(import18.ResponsiveState),this._appEl_67.vcRef);
    this._text_68 = this.renderer.createText(this._el_8,'\n       ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_8,'deviceInfo',(null as any));
    this._appEl_69 = new import3.AppElement(69,8,this,this._el_69);
    this._DeviceInfo_69_5 = new import14.Wrapper_DeviceInfo(this.parentInjector.get(import18.ResponsiveState),this._appEl_69.vcRef);
    this._text_70 = this.renderer.createText(this._el_8,'\n       ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_8,'orientationInfo',(null as any));
    this._appEl_71 = new import3.AppElement(71,8,this,this._el_71);
    this._OrientationInfo_71_5 = new import14.Wrapper_OrientationInfo(this.parentInjector.get(import18.ResponsiveState),this._appEl_71.vcRef);
    this._text_72 = this.renderer.createText(this._el_8,'\n       ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_8,'pixelratioInfo',(null as any));
    this._appEl_73 = new import3.AppElement(73,8,this,this._el_73);
    this._PixelRatioInfo_73_5 = new import15.Wrapper_PixelRatioInfo(this.parentInjector.get(import18.ResponsiveState),this._appEl_73.vcRef);
    this._text_74 = this.renderer.createText(this._el_8,'\n       ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_8,'userAgentInfo',(null as any));
    this._UserAgentInfo_75_3 = new import16.Wrapper_UserAgentInfo(this.parentInjector.get(import18.ResponsiveState));
    this._text_76 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_77 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_78 = this.renderer.createText(this._el_4,'\n',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_80 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._arr_0 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {bootstrap: p0};
    });
    this._arr_1 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._map_1 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {bootstrap: p0};
    });
    const subscription_0:any = this._Responsive_44_6.context.changes.subscribe(this.eventHandler(this._handle_changes_44_0.bind(this)));
    this._map_2 = import4.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        window: p0,
        min: p1,
        max: p2
      }
      ;
    });
    this._map_3 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {sizes: p0};
    });
    var disposable_0:Function = this.renderer.listen(this._el_67,'statechanges',this.eventHandler(this._handle_statechanges_67_0.bind(this)));
    const subscription_1:any = this._ResponsiveSizeInfo_67_5.context.statechanges.subscribe(this.eventHandler(this._handle_statechanges_67_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_69,'device',this.eventHandler(this._handle_device_69_0.bind(this)));
    const subscription_2:any = this._DeviceInfo_69_5.context.device.subscribe(this.eventHandler(this._handle_device_69_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_71,'orientation',this.eventHandler(this._handle_orientation_71_0.bind(this)));
    const subscription_3:any = this._OrientationInfo_71_5.context.orientation.subscribe(this.eventHandler(this._handle_orientation_71_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_73,'pixelratio',this.eventHandler(this._handle_pixelratio_73_0.bind(this)));
    const subscription_4:any = this._PixelRatioInfo_73_5.context.pixelratio.subscribe(this.eventHandler(this._handle_pixelratio_73_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_75,'info',this.eventHandler(this._handle_info_75_0.bind(this)));
    const subscription_5:any = this._UserAgentInfo_75_3.context.info.subscribe(this.eventHandler(this._handle_info_75_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._anchor_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4,
      subscription_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (42 === requestNodeIndex))) { return this._TemplateRef_42_5; }
    if (((token === import20.Responsive) && (42 === requestNodeIndex))) { return this._Responsive_42_6.context; }
    if (((token === import17.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import20.Responsive) && (44 === requestNodeIndex))) { return this._Responsive_44_6.context; }
    if (((token === import17.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import20.Responsive) && (49 === requestNodeIndex))) { return this._Responsive_49_6.context; }
    if (((token === import21.ResponsiveWindow) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ResponsiveWindow_47_3.context; }
    if (((token === import22.ResponsiveSizeInfo) && (67 === requestNodeIndex))) { return this._ResponsiveSizeInfo_67_5.context; }
    if (((token === import23.DeviceInfo) && (69 === requestNodeIndex))) { return this._DeviceInfo_69_5.context; }
    if (((token === import23.OrientationInfo) && (71 === requestNodeIndex))) { return this._OrientationInfo_71_5.context; }
    if (((token === import24.PixelRatioInfo) && (73 === requestNodeIndex))) { return this._PixelRatioInfo_73_5.context; }
    if (((token === import25.UserAgentInfo) && (75 === requestNodeIndex))) { return this._UserAgentInfo_75_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this._map_0(this._arr_0('xs','lg'));
    this._Responsive_42_6.check_responsive(currVal_0,throwOnChange,false);
    this._Responsive_42_6.detectChangesInternal(this,this._anchor_42,throwOnChange);
    const currVal_2:any = this._map_1(this._arr_1('xs','lg'));
    this._Responsive_44_6.check_responsive(currVal_2,throwOnChange,false);
    this._Responsive_44_6.detectChangesInternal(this,this._anchor_44,throwOnChange);
    const currVal_3:any = 'parent';
    this._ResponsiveWindow_47_3.check_name(currVal_3,throwOnChange,false);
    this._ResponsiveWindow_47_3.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_4:any = this._map_3(this._map_2('parent',900,1400));
    this._Responsive_49_6.check_responsive(currVal_4,throwOnChange,false);
    this._Responsive_49_6.detectChangesInternal(this,this._anchor_49,throwOnChange);
    this._ResponsiveSizeInfo_67_5.detectChangesInternal(this,this._el_67,throwOnChange);
    this._DeviceInfo_69_5.detectChangesInternal(this,this._el_69,throwOnChange);
    this._OrientationInfo_71_5.detectChangesInternal(this,this._el_71,throwOnChange);
    this._PixelRatioInfo_73_5.detectChangesInternal(this,this._el_73,throwOnChange);
    this._UserAgentInfo_75_3.detectChangesInternal(this,this._el_75,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Responsive_42_6.context.ngOnDestroy();
    this._Responsive_44_6.context.ngOnDestroy();
    this._Responsive_49_6.context.ngOnDestroy();
    this._ResponsiveWindow_47_3.context.ngOnDestroy();
    this._ResponsiveSizeInfo_67_5.context.ngOnDestroy();
    this._DeviceInfo_69_5.context.ngOnDestroy();
    this._OrientationInfo_71_5.context.ngOnDestroy();
    this._PixelRatioInfo_73_5.context.ngOnDestroy();
    this._UserAgentInfo_75_3.context.ngOnDestroy();
  }
  private _handle_changes_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.listenchanges($event)) !== false);
    return (true && pd_0);
  }
  private _handle_statechanges_67_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.mystates($event)) !== false);
    return (true && pd_0);
  }
  private _handle_device_69_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.thisdevice($event)) !== false);
    return (true && pd_0);
  }
  private _handle_orientation_71_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.thisorientation($event)) !== false);
    return (true && pd_0);
  }
  private _handle_pixelratio_73_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.thispixelratio($event)) !== false);
    return (true && pd_0);
  }
  private _handle_info_75_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.thisUserAgent($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent1,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','lead text-inf');
    this._text_2 = this.renderer.createText(this._el_1,'*Writing the documentation of this demo.',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_AppComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AppComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent2 extends import1.AppView<any> {
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent2,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this.init(([] as any[]),([] as any[]),([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_AppComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AppComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent3,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','fill');
    this.renderer.setElementAttribute(this._el_0,'style','color:white;font-size:20px;');
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_AppComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AppComponent3(viewUtils,parentInjector,declarationEl);
}